const firebaseConfig = {
  apiKey: REACT_APP_FIREBASE-APIKEY,
  authDomain: REACT_APP_FIREBASE-AUTHDOMAIN,
  projectId: REACT_APP_FIREBASE-PROJECTID,
  storageBucket: REACT_APP_FIREBASE-STORAGEBUCKET,
  messagingSenderId: REACT_APP_FIREBASE-MESSAGINGSENDERID,
  appId: REACT_APP_FIREBASE-APPID
}
  export default firebaseConfig